stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./docker/deploy/Dockerfile
      buildContext: .
      tag: ghcr.io/ringvold/teamsort
      pushRemote: true
      registry: ghcr.io
    when:
      branch:
        include:
        - master
      event:
        include:
        - push
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yml
    when:
      branch:
        include:
        - master
timeout: 60
notification: {}
