apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamsort
spec:
  replicas: 1
  selector:
    matchLabels:
      deploy: teamsort
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: teamsort
    spec:
      containers:
        - name: teamsort
          image: ghcr.io/ringvold/teamsort:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
              name: http
              protocol: TCP
