version: "3"

services:
  web:
    build: .
    command: mix phx.server
    # command: /bin/bash
    # user: "${UID}:${GID}"
    volumes:
      - .:/opt/app
      # - build:/opt/app/_build
      # - deps:/opt/app/deps
      # - node_modules:/opt/app/assets/node_modules
    ports:
      - "4000:4000"
    stdin_open: true
    tty: true

volumes:
  db-data:
  node_modules:
  build:
  deps:
