version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-dev
    environment:
      - PORT=4000
    volumes:
      - .:/home/elixir/app
      - /home/elixir/app/_build/
      - /home/elixir/app/deps/
    ports:
      - "4000:4000"
    stdin_open: true
    tty: true

volumes:
  build:
  deps:
